#ifndef FILTERPLUGINDESIGNER_GLOBAL_H
#define FILTERPLUGINDESIGNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILTERPLUGINDESIGNER_LIBRARY)
#  define FILTERPLUGINDESIGNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILTERPLUGINDESIGNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILTERPLUGINDESIGNER_GLOBAL_H
